// <file_info: file_map_generator.js>
/*
- Project: Sampo-MCP
- File: src/generators/file_map_generator.js
- Maps .js/.txt/.md files recursively in specified directories
- Outputs YAML format instead of JSON
- Ignores: hidden dirs (.), sandbox, node_modules
*/
// </file_info: file_map_generator.js>


// <block: imports>
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
// </block: imports>


// <block: helpers>
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function toForwardSlash(p) {
    return p.replace(/\\/g, "/");
}

function ensureDotSlash(p) {
    const fwd = toForwardSlash(p);
    return fwd.startsWith("./") ? fwd : `./${fwd}`;
}

function fmtISO_DDMMYYYYTHHMMSS(date = new Date()) {
    const pad = (n) => String(n).padStart(2, "0");
    const dd = pad(date.getDate());
    const mm = pad(date.getMonth() + 1);
    const yyyy = date.getFullYear();
    const HH = pad(date.getHours());
    const MM = pad(date.getMinutes());
    const SS = pad(date.getSeconds());
    return `${dd}.${mm}.${yyyy}T${HH}:${MM}:${SS}`;
}

function makeOutputSkeleton() {
    return {
        metadata: {
            timestamp: fmtISO_DDMMYYYYTHHMMSS(),
            description: "Autogenerated file mapping.",
            errors: false,
            error_message: null
        },
        files: {}
    };
}

function relFromCwd(fileAbs) {
    const rel = path.relative(process.cwd(), fileAbs);
    return ensureDotSlash(rel);
}

function baseNoExt(fileAbs) {
    return path.basename(fileAbs, path.extname(fileAbs));
}

async function writeYaml(filePath, dataObj) {
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    const yamlContent = generateYamlFromData(dataObj);
    await fs.writeFile(filePath, yamlContent, "utf-8");
    return filePath;
}

// Ignore patterns for directory scanning
function shouldIgnoreDir(dirName) {
    return dirName.startsWith(".") || dirName === "sandbox" || dirName === "node_modules";
}

// Recursive listing with ignore rules
async function listRecursiveJs(dirAbs) {
    const out = [];
    const entries = await fs.readdir(dirAbs, { withFileTypes: true });
    for (const e of entries) {
        const fullPath = path.join(dirAbs, e.name);

        if (e.isFile() && [".js", ".txt", ".md"].includes(path.extname(e.name).toLowerCase())) {
            out.push(fullPath);
        } 
        else if (e.isDirectory() && !shouldIgnoreDir(e.name)) {
            const subFiles = await listRecursiveJs(fullPath);
            out.push(...subFiles);
        }
    }
    return out;
}

// Generate YAML from data object
function generateYamlFromData(data) {
    const lines = [];
    
    lines.push("# FILE MAPPING");
    lines.push(`# Generated: ${data.metadata.timestamp}`);
    lines.push("");
    
    lines.push("# METADATA");
    lines.push("metadata:");
    lines.push(`  timestamp: "${data.metadata.timestamp}"`);
    lines.push(`  description: "${data.metadata.description}"`);
    lines.push(`  errors: ${data.metadata.errors}`);
    if (data.metadata.error_message) {
        lines.push(`  error_message: "${data.metadata.error_message}"`);
    } else {
        lines.push("  error_message: null");
    }
    if (data.metadata.output_file) {
        lines.push(`  output_file: "${data.metadata.output_file}"`);
    }
    lines.push("");
    
    lines.push("# FILES");
    lines.push("files:");
    
    const sortedKeys = Object.keys(data.files).sort();
    for (const key of sortedKeys) {
        lines.push(`  ${key}: "${data.files[key]}"`);
    }
    
    lines.push("");
    lines.push("# END");
    
    return lines.join("\n");
}
// </block: helpers>


// <block: core>
export async function mapFiles(inputDirs, options = {}) {
    const mode = options.mode ?? "module";
    const output = makeOutputSkeleton();
    const filesMap = output.files;
    const dupes = new Map(); // basename -> [paths]

    try {
        // Always include this script's own parent directory (src) - RECURSIVE
        const scanDirs = [path.dirname(__dirname)];

        // Add user-specified dirs (as given), also RECURSIVE
        const extra = (inputDirs ?? []).map((d) => path.resolve(process.cwd(), d));
        scanDirs.push(...extra);

        // Validate dirs
        for (const dir of scanDirs) {
            const stat = await fs.stat(dir).catch(() => null);
            if (!stat || !stat.isDirectory()) {
                throw new Error(`Not a directory: ${dir}`);
            }
        }

        // Collect recursive files
        const allFiles = [];
        for (const dir of scanDirs) {
            const top = await listRecursiveJs(dir); 
            allFiles.push(...top);
        }

        // Build mapping with duplicate detection
        for (const f of allFiles) {
            const key = baseNoExt(f);
            const rel = relFromCwd(f);
            if (Object.prototype.hasOwnProperty.call(filesMap, key)) {
                const prev = filesMap[key];
                if (!dupes.has(key)) dupes.set(key, [prev]);
                dupes.get(key).push(rel);
            } else {
                filesMap[key] = rel;
            }
        }

        if (dupes.size > 0) {
            output.metadata.errors = true;
            const msgs = [];
            for (const [k, arr] of dupes.entries()) {
                msgs.push(`Duplicate basename "${k}" detected in: ${arr.join(", ")}`);
            }
            output.metadata.error_message = msgs.join(" | ");
        }

        if (options.save) {
            const outDir = mode === "module"
                ? path.join(path.dirname(__dirname), "..", "data")
                : path.join(process.cwd(), "data");
            const outFile = path.join(outDir, "file_tree.yaml");
            await writeYaml(outFile, output);
            output.metadata.output_file = toForwardSlash(outFile);
        }
        
        // Generate file_paths.js if requested
        if (options.generatePaths) {
            const pathsFile = await generateFilePathsModule(filesMap);
            output.metadata.paths_file = toForwardSlash(pathsFile);
        }
    } catch (err) {
        output.metadata.errors = true;
        output.metadata.error_message = String(err?.message ?? err);
    }

    return output;
}
// </block: core>


// <block: cli>
async function runCli() {
    const args = process.argv.slice(2); // additional dirs to include (recursive)
    const result = await mapFiles(args, { 
        save: true, 
        generatePaths: false,  // Don't generate file_paths.js (deprecated)
        mode: "cli" 
    });
    
    // Output YAML to stderr instead of stdout to avoid polluting MCP JSON stream
    const yamlOutput = generateYamlFromData(result);
    process.stderr.write(yamlOutput + "\n");
    
    if (result.metadata.errors) process.exitCode = 2;
}

const isDirectRun = import.meta.url === pathToFileURL(process.argv[1])?.href;
if (isDirectRun) runCli();
// </block: cli>


// <block: generate_file_paths>
export async function generateFilePathsModule(filesMap) {
    const srcDir = path.dirname(__dirname);
    const outFile = path.join(srcDir, "file_paths.js");
    
    const lines = [];
    lines.push("// <file_info: file_paths.js>");
    lines.push("/*");
    lines.push("- Project: Sampo-MCP");
    lines.push("- File: src/file_paths.js");
    lines.push("- Auto-generated centralized path constants");
    lines.push("- DO NOT EDIT MANUALLY - regenerate with: node src/generators/file_map_generator.js");
    lines.push("- Generated: " + fmtISO_DDMMYYYYTHHMMSS());
    lines.push("- Usage: import { LOGGER } from './file_paths.js'; then import X from LOGGER;");
    lines.push("*/");
    lines.push("// </file_info: file_paths.js>");
    lines.push("");
	lines.push("// <block: imports/>");
	lines.push("");
    lines.push("// <block: path_mappings>");
    lines.push("// Path constants for centralized import management");
    lines.push("// When a file moves, update ONLY here - all imports stay valid");
    lines.push("");
    
    // Sort keys and group by directory for readability
    const sortedKeys = Object.keys(filesMap).sort();
    const byDir = new Map();
    
    for (const key of sortedKeys) {
        const relPath = filesMap[key];
        const fromSrc = relPath.replace(/^\.\/src\//, "./");
        const dir = path.dirname(fromSrc);
        
        if (!byDir.has(dir)) byDir.set(dir, []);
        byDir.get(dir).push({ key, path: fromSrc });
    }
    
    // Generate named exports grouped by directory
    for (const [dir, files] of byDir) {
        const dirName = dir === "." ? "Core modules" : dir.replace("./", "").replace(/\//g, " / ");
        lines.push(`// ${dirName}`);
        
        for (const { key, path: filePath } of files) {
            const constName = key.toUpperCase();
            lines.push(`export const ${constName} = "${filePath}";`);
        }
        lines.push("");
    }
    
    // Generate _PATHS object for dynamic lookups
    lines.push("// Object map for dynamic lookups (when you can't use import)");
    lines.push("export const _PATHS = {");
    
    for (const key of sortedKeys) {
        const constName = key.toUpperCase();
        lines.push(`    ${key}: ${constName},`);
    }
    
    lines.push("};");
    lines.push("// </block: path_mappings>");
    lines.push("");
    
    await fs.writeFile(outFile, lines.join("\n"), "utf-8");
    return outFile;
}
// </block: generate_file_paths>